#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

APP_NAME="apex-core"
WITH_TLS=1

step() { printf "\n\e[1;36m==> %s\e[0m\n" "$1"; }

show_help() {
  sed -n '1,24p' "$0" | sed 's/^# \{0,1\}//'
  exit 0
}

for arg in "$@"; do
  case "$arg" in
    --http) WITH_TLS=0 ;;
    --help|-h) show_help ;;
    *) echo "Unknown argument: $arg (try --help)"; exit 1 ;;
  esac
done

step "[1/2] Bundling the web interface (frontend)"
if [ ! -d frontend/node_modules ]; then
  echo "Installing frontend dependencies (first run)..."
  (cd frontend && npm install --no-audit --no-fund)
fi
(cd frontend && npm run build)

if [ "$WITH_TLS" = "1" ]; then
  step "[2/2] TLS certificates + compiling"
else
  step "[2/2] Compiling (HTTP mode)"
fi

VERSION="$(date +%Y.%m.%d)-$(git rev-parse --short HEAD 2>/dev/null || echo dev)"

# The production binary looks for tls/cert.pem & tls/key.pem by default
# and auto-generates self-signed certificates if they are missing or
# invalid — no openssl dependency needed at build time.
if [ "$WITH_TLS" = "1" ]; then
  mkdir -p tls
  echo "Certificates are auto-generated by the binary on first run (tls/cert.pem, tls/key.pem)."
  echo "  To supply your own certificates, place them at tls/cert.pem and tls/key.pem."
else
  echo "Plain HTTP build — no TLS artifacts created."
fi

# CGO_ENABLED=0 produces a fully static binary. -trimpath strips local
# build paths; -ldflags "-s -w" strips symbol/debug tables.
CGO_ENABLED=0 go build -trimpath \
  -ldflags "-s -w -X 'main.buildVersion=${VERSION}'" \
  -o "${APP_NAME}" .

echo
echo "============================================================"
echo "  APEX CORE build complete  (version: $VERSION)"
echo "  binary: $ROOT/$APP_NAME"
[ "$WITH_TLS" = "1" ] && echo "  TLS key/cert: $ROOT/tls/key.pem / $ROOT/tls/cert.pem (auto-generated on first run)"
echo "============================================================"
echo
echo "  PRODUCTION (HTTPS):"
echo "    ./apex-core"
echo
echo "  DEVELOPMENT (no rebuild needed):"
echo "    go run main.go"
echo "    cd frontend && npm run dev"
echo