@echo off
setlocal EnableExtensions EnableDelayedExpansion

REM ============================================================
REM APEX CORE - Windows Single Binary Build Script
REM ============================================================

cd /d "%~dp0"

set "ROOT=%CD%"
set "APP_NAME=apex-core"
set "WITH_TLS=1"

if "%~1"=="--http" (
    set "WITH_TLS=0"
    shift
)

if "%~1"=="--help" goto :help
if "%~1"=="-h" goto :help
if not "%~1"=="" (
    echo ERROR: Unknown argument: %~1
    echo Try --help for usage information.
    exit /b 1
)

echo.
echo ============================================================
echo   APEX CORE - Windows Build
echo ============================================================
echo.

REM ============================================================
REM [1/2] Build frontend
REM ============================================================

echo [1/2] Bundling the web interface ^(frontend^)...
echo.

if not exist "frontend\node_modules" (
    echo Installing frontend dependencies ^(first run^)...
    cd frontend
    call npm install --no-audit --no-fund
    if errorlevel 1 (
        echo ERROR: Frontend dependency installation failed.
        exit /b 1
    )
    cd ..
)

cd frontend
call npm run build
if errorlevel 1 (
    echo ERROR: Frontend build failed.
    exit /b 1
)
cd ..

REM ============================================================
REM [2/2] TLS certificates + compile
REM ============================================================

if "%WITH_TLS%"=="1" (
    echo.
    echo [2/2] TLS certificates + compiling...
    echo.

    if not exist "tls" mkdir tls
    echo Certificates are auto-generated by the binary on first run ^(tls\cert.pem, tls\key.pem^).
    echo   To supply your own certificates, place them at tls\cert.pem and tls\key.pem.
) else (
    echo.
    echo [2/2] Compiling ^(HTTP mode^)...
    echo.
)

REM ============================================================
REM Compile single Windows executable (root directory)
REM ============================================================

set "VERSION="

for /f "delims=" %%V in ('powershell -NoProfile -Command "(Get-Date).ToString('yyyy.MM.dd')"') do (
    set "VERSION=%%V"
)

git rev-parse --short HEAD >nul 2>&1
if not errorlevel 1 (
    for /f "delims=" %%H in ('git rev-parse --short HEAD') do (
        set "VERSION=!VERSION!-%%H"
    )
) else (
    set "VERSION=!VERSION!-dev"
)

echo Build version: !VERSION!

set "LDFLAGS=-s -w -X main.buildVersion=!VERSION!"

go build -trimpath -ldflags "!LDFLAGS!" -o "%APP_NAME%.exe" .

if errorlevel 1 (
    echo.
    echo ERROR: Go compilation failed.
    exit /b 1
)

echo.
echo ============================================================
echo   APEX CORE build complete
echo   Version: !VERSION!
echo   Binary: %ROOT%\%APP_NAME%.exe
if "%WITH_TLS%"=="1" (
    echo   TLS key/cert: %ROOT%\tls\key.pem / %ROOT%\tls\cert.pem ^(auto-generated on first run^)
)
echo ============================================================
echo.
echo PRODUCTION ^(HTTPS^):
echo   %APP_NAME%.exe
echo.
echo DEVELOPMENT ^(no rebuild needed^):
echo   go run main.go
echo   cd frontend ^&^& npm run dev
echo.
exit /b 0

REM ============================================================
REM HELP
REM ============================================================

:help
echo.
echo APEX CORE - Windows Build Script
echo.
echo Usage:
echo   build.bat
echo   build.bat --http
echo   build.bat --help
echo.
echo Options:
echo   --http    Build without TLS certificate generation.
echo   --help    Display this help message.
echo.
exit /b 0
